feat: allow use of server.name as server_id argument  (#11)
This PR modifies parser for operations that accept an integer server_id
path parameter to accept a string command-line argument. For example, if
account has a server named `foo-bar.bnr.la` here are some example
commands that are now valid:

```
bl server get foo-bar.bnr.la
bl server delete foo-bar.bnr.la
bl server console foo-bar.bnr.la
bl server action reboot foo-bar.bnr.la
```

During parsing, if the command-line argument provided for `server_id`
cannot be converted to integer (i.e. `int(argument)` raises ValueError)
then the argument is assumed to be the name of a server. The `server
list` operation is used to fetch all servers, and the result filtered to
find the integer ID of the server with `name == argument`.

If there is no such server, the parser displays an error:

```
error: SERVER: cound not find 'foo-bar.bnr.la'
```